apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: mi-web
    version: v2  # Aquí selecciona AMBOS deployments
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer