apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: canary-demo
  labels:
    app: nginx
spec:
  type: LoadBalancer      # Expone la app con IP pública en GKE
  selector:
    app: nginx            # ← Enruta a TODOS los pods con label "app: nginx" (v1 + v2)
                          #   La distribución de tráfico es proporcional a las réplicas:
                          #   4 pods v1 + 1 pod v2 = 80% v1, 20% v2
  ports:
  - name: http
    protocol: TCP
    port: 80              # Puerto externo (el que usas en el navegador)
    targetPort: 80        # Puerto interno del contenedor Nginx